### PR TITLE
Allow HTML in progress text

### PR DESCRIPTION
**Pull request by ghost**
This edit needs to be compiled into the final JS files - but basically this lets you add HTML inside the progress text dynamically.
I encountered this problem when I needed the text to contain a number and below it another number and in a different color & smaller.

### CODE REVIEW

**Comment by kimmobrunfeldt** [comment]
I really much like this PR, but I'd like to think this thoroughly before merging / implementing. I would like to remove the 'text' concept totally and replace it with any custom html element as you have done here. I'll look into this at some day and probably contribute to this too. Thanks for the PR.

**Comment by sxasraf** [comment]
@kimmobrunfeldt well to be honest, I just had to use it - and it works well for me for now. Thing is you have to style it yourself. I would probably consider at least adding a default low-priority style to what you put inside.

**Comment by vwasteels** [comment]
Hello, are you going to merge this branch soon ? thank you !!

**Comment by josephmuli** [comment]
naah I'm on some heavy stuff right now

**Comment by vwasteels** [comment]
ok thanks :)
If someone is looking for this feature, I forked it here :
https://github.com/vwasteels/progressbar.js

**Comment by kimmobrunfeldt** [comment]
@vwasteels I don't know what @josephmuli is talking about, he is not a contributor of the project. I haven't merged this PR because it would need further designing. One option would be to extend the current `text` option to support arbitrary HTML too.

In the meanwhile people can use @vwasteels fork to enable this feature.

**Comment by vwasteels** [comment]
haha ok, well the ```setHtml()``` option works too, but you're right it would be better if it was built in with the ```text```option :)

**Comment by kimmobrunfeldt** [comment]
Update to this: I yesterday worked with this functionality. My current plan is to keep the existing API but to allow html in the text string or optionally pass an DOM element.

**Comment by kimmobrunfeldt** [comment]
Setting HTML is now possible in 1.0.0 release. It can be done via text values. See release notes: https://github.com/kimmobrunfeldt/progressbar.js/releases/tag/1.0.0

**Comment by kimmobrunfeldt** [comment]
If this leads to worse performance in practice, please open a new issue.

**Pull request closed without merging**
