### PR TITLE
Added a reference to ProgressBar.Path instance to arguments for step function

### LINKED ISSUE #48: The instance of the ProgressBar Shape/Path should be accessible from the step function.
Unless i missed something, when using `ProgressBar.Path` there is no way to get the reference to itself from the `step` function supplied in instantiation unless using some round about referencing method. I would propose this also be passed as an argument to `step` or merged in to the `state` provided to step. 

Example usage would be to animate a progress bar on an irregular shaped custom path (like an arc) and also animate some text like a counter (similar to what is built in to circle and line) and might be achieved with the following:

    var svgPath = document.getElementById('svgPath'),
          counter = document.getElementById('counter');

    var p = new ProgressBar.Path(svgPath, {
          duration: 800,
          from: { strokeOffset: svgPath.getTotalLength() },
          to: { strokeOffset: 0 },
          attachment: { path: svgPath, counter: counter },
          // here self would be a ref to the ProgressBar.Path instance
          step: function (state, attachment, self) {
              attachment.path.setAttribute('strokeOffset', state.strokeOffset);
              attachment.counter.innerHTML = (self.value()*100);
          }
    });

    p.animate(0.75);

### PR DESCRIPTION
**Pull request by prodigitalson**
Also added sinon dev dep for spying on step function and test cases for ProgressBar.Path. Fixes #48.

### CODE REVIEW

**Comment by kimmobrunfeldt** [comment]
Really good work! :) I'll merge this after the new parameter is documented.

**Comment by prodigitalson** [comment]
Ok updated the PR as discussed. I also renamed the behaviour files for the tests so they were a bit more semantic given that we now run tests on the low-level Path API. I also ran across an issue with testem in that it was picking up the browserify-tests.js in it watch and just kept endlessly running. I changed the glob in the config to just look at `test-*.js` instead.

**Comment by kimmobrunfeldt** [comment]
Everything looks good and big :+1: for the additional tests! There's one more thing I'd ask before the merge, could you change tab indentations to 4 spaces? That's the style convention in the project. I noticed tabs at least in some parts of test/path-behaviour.js

**Comment by prodigitalson** [comment]
@kimmobrunfeldt Sorry about that... another project I am on uses hard tabs and didn't think to switch my editor prefs initially. Should be all fixed up now.

**Comment by kimmobrunfeldt** [comment]
Thanks! Good to merge

**Comment by kimmobrunfeldt** [comment]
After merging this PR, I get error in Travis: https://travis-ci.org/kimmobrunfeldt/progressbar.js/builds/55414135. I didn't watch the failing code at all yet, I can investigate this later but I thought you might now why this happens.

It outputs this error:
```
Chrome 38.0.2125 (Linux) Path "before each" hook FAILED
	TypeError: Cannot read property 'setAttribute' of null
	    at Object.createPath (/tmp/2a5f2229cdb77be15daf9868295fa600265bf1a4.browserify:14830:14 <- /home/travis/build/kimmobrunfeldt/progressbar.js/test/path-behaviour.js:34:0)
	    at Context.<anonymous> (/tmp/2a5f2229cdb77be15daf9868295fa600265bf1a4.browserify:15203:31 <- /home/travis/build/kimmobrunfeldt/progressbar.js/test/test-all.js:80:0)
Chrome 38.0.2125 (Linux) Path "before each" hook FAILED
	TypeError: Cannot read property 'setAttribute' of null
	    at Object.createPath (/tmp/2a5f2229cdb77be15daf9868295fa600265bf1a4.browserify:14830:14 <- /home/travis/build/kimmobrunfeldt/progressbar.js/test/path-behaviour.js:34:0)
	    at Context.<anonymous> (/tmp/2a5f2229cdb77be15daf9868295fa600265bf1a4.browserify:15203:31 <- /home/travis/build/kimmobrunfeldt/progressbar.js/test/test-all.js:80:0)
..
```

Currently Travis runs tests for PRs with PhantomJS so the test failed when run in sauce labs with real browsers.

**Comment by prodigitalson** [comment]
@kimmonrunfeldt hmm not sure, all the tests passed for me on the CLI and in the browser. I'll have to take a look.

**Comment by prodigitalson** [comment]
@kimmobrunfeldt So it seems that `document.getElementById('container')` is returning `null` on the travis builds. This is used in order to get the container so I can append custom SVG path for the `ProgressBar.Path` test cases. I am not really sure why that is an issue since i would also expect all the Shape tests to fail since they depend on the same element, yeah?

**Pull request merged**
