### PR TITLE
Remove moot `version` property from bower.json

### PR DESCRIPTION
**Pull request by kkirsche**
Per bower/bower.json-spec@a325da3

### CODE REVIEW

**Comment by kimmobrunfeldt** [comment]
This version is automatically managed so it's not more work to manage it. Is it a bad thing to also have version number in bower.json? To my mind sounds like it doesn't matter

**Comment by kkirsche** [comment]
Is it bad? No. But considering bower core development is basically dead and the recommendation is to use NPM, I wouldn't want to encourage users to rely on bower or unused properties in those files.

**Comment by kimmobrunfeldt** [comment]
Ok. Well then I have to remove bower.json from build tools too. I'll contribute to this PR at somepoint.

**Comment by kimmobrunfeldt** [comment]
This PR moved to: https://github.com/kimmobrunfeldt/progressbar.js/pull/84

**Pull request closed without merging**
