### PR TITLE
Exposing the Square API

### PR DESCRIPTION
**Pull request by stramel**
Noticed the square API sitting out there not exposed so I linked it up and tests added.

I also added the compiled version but that can be reverted if I shouldn't have commited the compiled version.

### CODE REVIEW

**Comment by stramel** [comment]
@kimmobrunfeldt Ping

**Comment by stramel** [comment]
@kimmobrunfeldt Friendly Ping

**Comment by stramel** [comment]
@kimmobrunfeldt Please merge

**Comment by stramel** [comment]
@kimmobrubfeldt _*crickets*_

**Comment by stramel** [comment]
@kimmobrunfeldt Please can you merge this and release?

**Comment by kimmobrunfeldt** [comment]
Sorry for taking so long. I haven't had a lot of time to do open source lately.

**Pull request merged**
