### PR TITLE
Add support for pause/resume

### PR DESCRIPTION
**Pull request by JieJiSS**
this function will not break the previous APIs.

Pause/Resume function is useful for:

+ Download/Upload progress
+ Timer & Countdown
+ Audio & Video progress bar
+ ...

### CODE REVIEW

**Comment by JieJiSS** [comment]
Well, it seems that the travis-ci test failed because of issues that are not related to this pr.

**Comment by kimmobrunfeldt** [comment]
Thanks for the contribution. This looks like a good addition, could you add a test case for this also?

Tests should work locally. Unfortunately the CI tests are broken at the moment as we test against real browsers. That requires quite regular maintenance.

**Comment by JieJiSS** [comment]
@kimmobrunfeldt Test case added, and it passed on my PC:

```shell
---- Linting code..


> progressbar.js@1.0.1-dev lint /Users/jiejiss/Work/Code/js/progressbar.js
> ./tools/lint.sh


> progressbar.js@1.0.1-dev jscs /Users/jiejiss/Work/Code/js/progressbar.js
> jscs ./src ./test


> progressbar.js@1.0.1-dev eslint /Users/jiejiss/Work/Code/js/progressbar.js
> eslint --ext .js ./src ./test


---- Running tests..

Running "shell:testem" (shell) task

  .............................................................
  ........

  69 tests complete (15691 ms)


Done, without errors.
```

**Comment by kimmobrunfeldt** [comment]
Thank you!

**Comment by kimmobrunfeldt** [comment]
Delay option is now available in the latest version.

**Pull request merged**
