### PR TITLE
Added onStep callback to animation

### PR DESCRIPTION
**Pull request by sixlive**
Added Math.round10 function. Added onStep callback to the animate function.

### CODE REVIEW

**Comment by sixlive** [comment]
Not looking for direct merge on this, more of a discussion point / proposal.

I needed a callback to be able to print the status of the animation. Not sure if this is a total one off thing that I needed or something that there might be some interest for others. I'd be willing to go through the proper contributing code process if there is interest in this.

Example usage:
```javascript
var circle = new ProgressBar.Circle('#progress-bar', {
    color: '#FCB03C',
    strokeWidth: 1,
});

circle.animate((55 * Number('.01')), {
  duration: 1200,
  onStep: function(args) {
    document.getElementById('score-count').innerHTML = Math.round((args.value * 100));
  }
}, function() {
 // Complete callback
});
```

Thanks for the awesome lib!

**Comment by kimmobrunfeldt** [comment]
Thanks for the effort, but there already is functionality like this. See API documentation for .animate() method: https://github.com/kimmobrunfeldt/progressbar.js#pathanimateprogress-options-cb

You probably want to read this section too https://github.com/kimmobrunfeldt/progressbar.js#custom-animations

Here's an actual demo of the usage of custom step function http://kimmobrunfeldt.github.io/progressbar.js/#example-custom-animation

**Comment by sixlive** [comment]
@kimmobrunfeldt wow, boy do I feel like a dummy, I TOTALLY missed that. I guess thats what I get coding on a few hours of sleep a few days in a row.

Thanks for this!

**Comment by kimmobrunfeldt** [comment]
No problem! :)

**Pull request closed without merging**
