### PR TITLE
Upgrade Shifty to 2.1.2

### PR DESCRIPTION
**Pull request by jeremyckahn**
Hi @kimmobrunfeldt!  This PR upgrades progressbar.js to the latest version of Shifty.  Among other things, Shifty offers [significantly improved performance over 1.x](https://codepen.io/jeremyckahn/pen/prMYXj).

I was able to the run the CLI tests locally and get them to pass, but I wasn't able to fully install all of the dependencies and I couldn't quite run the modified code in my browser.  I can spend a little more time with trying to get this working on my machine (there's probably some environment-specific weirdness going on), but please let me know if this works for you.  Thanks!

### CODE REVIEW

**Comment by jeremyckahn** [comment]
Oh, look at that — the tests are failing because [PhantomJS doesn't support Promises](https://github.com/ariya/phantomjs/issues/12401) (which Shifty now leverages).  The test environment will need to be polyfilled to support it — I can try to make that happen when I get some time.

**Comment by jeremyckahn** [comment]
I updated my PR with newer dependencies so I am able to get things to run and pass on my machine.  However, the tests on Travis are still failing because of Phantom not defining `Promise`.  I don't have any access to that environment — @kimmobrunfeldt, is that something you can address?

**Comment by kimmobrunfeldt** [comment]
Hi, thanks for the awesome work. I'll merge this for now in master so it won't be forgotten. I'd also like to support promises in the progressbar.js API, but the PR is perfect now since it doesn't change the callback style.

Travis tests are a bit broken unfortunately.

**Comment by jeremyckahn** [comment]
Yay, thanks for merging! Progressbar.js is far and away the biggest consumer of Shifty, so I'm really excited to see this get merged.  Thanks for leading such an awesome project!

**Pull request merged**
